_metadata:
  major_version: 1
  minor_version: 1
display_information:
  name: SecZetta
features:
  bot_user:
    display_name: Slackdemo
    always_online: false
oauth_config:
  scopes:
    bot:
      - chat:write
      - users.profile:read
      - users:read
      - users:write
      - chat:write.customize
      - chat:write.public
settings:
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
